
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homebaze_app
    user: "1000:1000"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - homebaze_network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: homebaze_nginx
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - homebaze_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: homebaze_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homebaze
      MYSQL_USER: homebaze_user
      MYSQL_PASSWORD: homebaze_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - homebaze_network

  redis:
    image: redis:7-alpine
    container_name: homebaze_redis
    ports:
      - "6380:6379"
    networks:
      - homebaze_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: homebaze_phpmyadmin
    ports:
      - "8091:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    networks:
      - homebaze_network
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog:latest
    container_name: homebaze_mailhog
    ports:
      - "1026:1025"
      - "8093:8025"
    networks:
      - homebaze_network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homebaze_queue
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    networks:
      - homebaze_network
    depends_on:
      - mysql
      - redis

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homebaze_scheduler
    command: supercrond
    volumes:
      - .:/var/www/html
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - homebaze_network
    depends_on:
      - mysql
      - redis

networks:
  homebaze_network:
    driver: bridge

volumes:
  mysql_data:
